[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"

[dev]
  command = "npm run dev:vite"
  targetPort = 5173
  autoLaunch = false

[functions]
  directory = "netlify/functions"
  node_bundler = "none"
  [functions."*"]
    timeout = 26

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
